---
title: Check Merge vs. Combined TARGET Pilot GTF and Junction files
author: "Cindy Liang (celiang@ucsc.edu)"
format:
  gfm:
    df-print: kable
editor_options:
  markdown:
    wrap: sentence
date: "`r format(Sys.time(), '%B %d, %Y')`"
---

## Read in directories and files

Define directories and file paths

```{r}
### Directories ###
## combined shiba run results on target pilot samples ##
# shiba results dir
combined_results_dir <- file.path("exploration", "merging-psi-tables", "target_pilot", "shiba_combined")
# junctions dir
combined_junctions_dir <- file.path(combined_results_dir, "junctions")
# gtf dir
combined_gtf_dir <- file.path(combined_results_dir, "annotation")

## merged shiba run results on target pilot samples ##
# shiba results dir
merged_results_dir <- file.path("results", "merged_shiba", "target_pilot")

### Files ###
## combined shiba target pilot files
combined_gtf_file <- file.path(combined_gtf_dir, "assembled_annotation.gtf")
combined_junctions_file <- file.path(combined_junctions_dir, "junctions.bed")

## merged shiba target pilot files
merged_gtf_file <- file.path(merged_results_dir, "merged_gtf.gtf")
merged_junctions_file <- file.path(merged_results_dir, "merged_junctions.bed")
```

Read in files

```{r}

# read in files generated from combined shiba run
combined_junctions <- readr::read_tsv(
  combined_junctions_file,
  col_types = readr::cols(
    .default = "d",
    ID = "c",
    chr = "c",
    start = "d",
    end = "d"
  )
)

# read in files generated from merged shiba run
merged_junctions <- readr::read_tsv(
  merged_junctions_file,
  col_types = readr::cols(
    .default = "d",
    ID = "c",
    chr = "c",
    start = "d",
    end = "d"
  )
)


```

Check tables for parsing errors
```{r}
combined_junctions_dat <- vroom::vroom(combined_junctions_file)
vroom::problems(combined_junctions_dat)
```

```{r}
merged_junctions_dat <- vroom::vroom(merged_junctions_file)
vroom::problems(merged_junctions_dat)
```

## Check if files are identical

### Check if combined and merged junctions.bed files are identical

```{r}
identical(combined_junctions, merged_junctions)
```

## Check differences in junctions bedfiles
Dimensions of each bedfile
```{r}
dim(combined_junctions)
```
```{r}
dim(merged_junctions)
```

Elements unique to each junction bedfile

```{r}
# elements in combined junctions df but not in merged
junctions_unique_to_combined <- setdiff(combined_junctions, merged_junctions)
head(junctions_unique_to_combined)

```

```{r}
# elements in combined junctions df but not in merged
junctions_unique_to_merged <- setdiff(merged_junctions, combined_junctions)
head(junctions_unique_to_merged)

```