# replace SAMPLE_GROUP with "target" or "gtex" depending on group of files to be preprocessed
sample_group: gtex
# if the samples list is empty, all samples for the sample group found in the data directory will be run
samples: [SRR601500]

genome_id: gencode.v47.primary_assembly
genome_assembly: GRCh38.primary_assembly.genome
genome_fasta_url: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_47/GRCh38.primary_assembly.genome.fa.gz
genome_gtf_url: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_47/gencode.v47.primary_assembly.annotation.gtf.gz
