[workspace]
authors = ["Cindy Liang <celiang@ucsc.edu>"]
channels = ["conda-forge", "bioconda"]
name = "shiba"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
shiba = "==0.8.1"
star = "==2.7.9a"
r-base = "==4.4.2"
snakemake = ">=9.6.2,<10"
quarto = ">=1.7.32,<2"
sra-tools = ">=3.2.1,<4"
r-renv = ">=1.1.5,<2"
fastp = ">=1.0.1,<2"
samtools = ">=1.22.1,<2"
pigz = ">=2.8,<3"
graphviz = ">=12.2.1,<13"
rsync = ">=3.4.1,<4"
