---
title: "R Notebook"
output: html_notebook
---

merge sample psi tables 

load packages
```{r}
suppressPackageStartupMessages({
  library(optparse)
  library(dplyr)
})
```

read in file paths

```{r read_files}
## Directories ##
# find project root to access separate results dir
repo_root <- rprojroot::find_root(rprojroot::is_git_root)

# result directories
results_dir <- file.path(repo_root, "results")
compendium_results_dir <- file.path(results_dir, "merged_shiba")
version_dir <- file.path(compendium_results_dir, "v1.1.0_two_sample")
psi_dir <- file.path(version_dir, "sample_psi")

# sample sheet dir
config_dir <- file.path(repo_root, "config")

# merged psi table output dir
output_dir <- file.path(version_dir, "merged_psi")

# create output dir if it does not exist
if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
}


## Files ##

# sample sheet file with sample names
samples_file <- file.path(config_dir, "two_sample_merge_samples.tsv")

# read in sample sheet and create list of samples from samples column
samples <- readr::read_tsv(samples_file, col_types = list(.default = "c")) |>
  dplyr::pull(sample) |>
  as.list()

# define list of PSI results files corresponding to event types quantified by Shiba bulk analysis
psi_file_list <- c(
  se = "PSI_SE.txt",
  afe = "PSI_AFE.txt",
  ale = "PSI_ALE.txt",
  five = "PSI_FIVE.txt",
  three = "PSI_THREE.txt",
  mse = "PSI_MSE.txt",
  mxe = "PSI_MXE.txt",
  ri = "PSI_RI.txt"
)

# make sample psi table paths
sample_paths <- file.path(
  psi_dir,
  samples
)

# output files
out_file_list <- c(
  se = "PSI_SE.txt",
  afe = "PSI_AFE.txt",
  ale = "PSI_ALE.txt",
  five = "PSI_FIVE.txt",
  three = "PSI_THREE.txt",
  mse = "PSI_MSE.txt",
  mxe = "PSI_MXE.txt",
  ri = "PSI_RI.txt",
  matrix = "PSI_matrix_sample.txt",
  all_events = "all_events_PSI.txt"
)

# construct output file paths
out_paths <- file.path(
  output_dir,
  out_file_list
)

# pass out_file_list names to output paths so purrr can match them up
names(out_paths) <- names(out_file_list)
```

Define functions to read in psi files

```{r}
# function for reading all sample PSI tables into one PSI table per event type
read_psi_to_event_tables <- function(psi_path, psi_files = psi_file_list) {
  # returns a data frame per event type with all 
  # construct file path for event type
  file_paths <- file.path(psi_path, psi_files)
  # name each PSI table file path by event type
  names(file_paths) <- names(psi_files)

  # merge all event types together for analysis
  purrr::map(file_paths, \(file) {
    readr::read_tsv(file, col_types = readr::cols(.default = "c"))
  })
}

# function for reading all sample PSI matrix ("PSI_matrix_sample.txt")
read_sample_psi_matrix <- function(psi_path) {
  # returns a PSI matrix data frame of all samples in sample sheet
  # with
  file_paths <- file.path(psi_path, "PSI_matrix_sample.txt")
  # merge psi matrix files together 
  purrr::map(file_paths, \(file) {
    readr::read_tsv(file, col_types = readr::cols(.default = "c"))
  }) |>
    dplyr::bind_rows()
}

# Make function for reading all PSI tables for a sample (or set of samples run together) into one PSI table with all event types
read_psi_to_one_table <- function(psi_path, psi_files = psi_file_list) {
  # construct file path for event type
  file_paths <- file.path(psi_path, psi_files)
  # name each PSI table file path by event type
  names(file_paths) <- names(psi_files)

  # merge all event types together for analysis
  purrr::map(file_paths, \(file) {
    readr::read_tsv(file, col_types = readr::cols(.default = "c")) |>
      # select for columns that will be used downstream in analysis so all dataframes have uniform column names
      dplyr::select(pos_id, gene_id, label, contains("_PSI")) |>
      # transform so we get a long table of PSI values for each event type, with one row per position and sample
      tidyr::pivot_longer(
        cols = contains("_PSI"),
        names_to = "sample",
        values_to = "psi",
        values_transform = as.numeric
      )
  }) |>
    # merge individual event type PSI tables to get one PSI table per sample
    dplyr::bind_rows(.id = "event_type")
}
```

Read in and merge PSI files from all samples
```{r}
# tables that mirror shiba outputs
merged_separate_events <- read_psi_to_event_tables(sample_paths, psi_file_list)
merged_matrix <- read_sample_psi_matrix(sample_paths)
# nice psi table output intended for adding gene names and downstream evaluation
merged_all_events <- read_psi_to_one_table(sample_paths, psi_file_list)

# roll outputs into a list for writing outputs with purrr
all_outputs <- c(
  # already a named list
  merged_separate_events,
  # add merged matrix and all events table to the list, giving them the same names as out_paths
  list(matrix = merged_matrix, all_events = merged_all_events)
)

# give purrr iwalk the list of named output files and write output using named output paths
purrr::iwalk(all_outputs, \(df, name) {
  readr::write_tsv(df, out_paths[[name]])
})

```


