---
title: Merge Shiba PSI tables
author: "Cindy Liang (celiang@ucsc.edu)"
format:
  gfm:
    df-print: kable
editor_options:
  markdown:
    wrap: sentence
date: "`r format(Sys.time(), '%B %d, %Y')`"
---

Shiba is run one sample at a time using our snakemake workflow. 
We then merge PSI tables produced for each sample.

## Set up

## Directories and files

```{r define_paths}

# samples list
# noting here that it will become terrible to paste infinite sample names in this list
# so maybe we want to ultimately have the script read in a file with all the samples for the big run
samples <- c("SRR601500", "SRR604528")

# find the project directory
base_dir <- here::here()

# define the data directories
# splice results directory
results_dir <- file.path(base_dir, "results")

# general shiba results paths
shiba_gtex_path <- file.path(results_dir, "gtex/shiba")
splice_results_path <- "results/splicing"

# make sample paths
sample_paths <- file.path(
    shiba_gtex_path,
    samples,
    splice_results_path
  )

# define list of PSI results files corresponding to event types quantified by Shiba bulk analysis
psi_files <- c(
  se = "PSI_SE.txt.gz",
  afe = "PSI_AFE.txt.gz",
  ale = "PSI_ALE.txt.gz",
  five = "PSI_FIVE.txt.gz",
  three = "PSI_THREE.txt.gz",
  mse = "PSI_MSE.txt.gz",
  mxe = "PSI_MXE.txt.gz",
  ri = "PSI_RI.txt.gz"
)

# name the outer list of paths by sample ID
# names(sample_psi_result_paths) <- samples

# output directory of results
out_dir <- file.path(results_dir, "merged_shiba_results_tables")

# output merged file for test samples
out_file <- file.path(out_dir, "merged_psi_table.tsv")

# create output directory if it does not already exist
dir.create(out_dir, showWarnings = FALSE)
```

Define functions
```{r}
# Make function for reading event types for a single sample
read_sample <- function(sample_id, sample_path, psi_files) {
  # construct file path for each sample
  file_paths <- file.path(sample_path, psi_files)
  # name each PSI table file path by event type
  names(file_paths) <- names(psi_files)
  
  # read in files
  purrr::map(file_paths, \(file) {
    readr::read_tsv(file, col_types = readr::cols(.default = "c")) |>
    # select for columns that will be used downstream in analysis so all dataframes have uniform column names
        dplyr::select(pos_id, gene_id, label, contains("_PSI"))
  }) |>
    # merge individual event type PSI tables to get one PSI table per sample
    dplyr::bind_rows(.id = "event_type")
}
  
```

Read in files

```{r read_in_files}

# read in one samples' PSI table
# take in list of samples and sample paths as input
sample_psi_tables <- purrr::map2(
  samples, 
  sample_paths, 
  # read in one sample and one sample path at a time
  \(sample, sample_path){read_sample(sample, sample_path, psi_files=psi_files)}
  ) |>
  # name the list of data frames the sample names
  purrr::set_names(samples)

```

Combine PSI dataframes for all samples into one

```{r}
# combine individual event types' PSI tables into one 
merged_psi <- sample_psi_tables |>
  purrr::reduce( \(x, y) {
    dplyr::full_join(x, y, by = c("pos_id", "gene_id", "label", "event_type") )
  }
  )

```

Save output as a table
```{r}
readr::write_tsv(merged_psi, out_file)
```
