---
title: "Test Wilcoxon ranksums on TARGET subset"
author: "Cindy Liang (celiang@ucsc.edu)"
format:
  gfm:
    df-print: kable
editor_options:
  markdown:
    wrap: sentence
date: "`r format(Sys.time(), '%B %d, %Y')`"
---

## Set up
## Directories and files

```{r}
# find the root-level repo directory
repo_root <- rprojroot::find_root(rprojroot::is_git_root)

# define the data directories
# exploration dir
exploration_dir <- file.path(repo_root, "exploration/compare_psi_distributions")
data_dir <- file.path(exploration_dir, "data")

# target subset metadata
target_metadata_file <- file.path(data_dir, "SraRunTable-TARGET.csv")
# target subset combined psi results
combined_psi_file <- file.path(data_dir, "combined_psi_results.rds")

```

## read in files

```{r}
# read in TARGET sample metadata
target_metadata <- readr::read_csv(target_metadata_file)

# combined PSI results from notebook 01-target_subset_psi_value_comparison
psi_combined <- readRDS(combined_psi_file)
```

## Combine PSI table with TARGET metadata to associate samples with cancer type
```{r}

# We only care about body site and run fields in target metadata
filtered_target_metadata <- target_metadata |>
  dplyr::select(study_name, Run) |>
  dplyr::filter(grepl("TARGET", study_name)) |>
  dplyr::mutate(Run = paste0(Run, "_PSI"))

# we need to associate the body site with accession number, so first pivot the table longer (so that we are back to one column of just accession IDs)
cancer_type_psi_table <- psi_combined |>
  tidyr::pivot_longer(
    cols = contains("_PSI"),
    names_to = "Run",
    values_to = "PSI"
    ) |>
  dplyr::inner_join(
    filtered_target_metadata, 
    by = c("Run")) |>
  # assign group type (ref vs query)
    dplyr::mutate(
    group = dplyr::case_when(
      study_name ==  "TARGET: Kidney\\, Wilms Tumor (WT)" ~ "query",
      study_name !=  "TARGET: Kidney\\, Wilms Tumor (WT)" ~ "ref"
    )
  )

```

Calculate Wilcoxon ranksum for PSI distributions
```{r}

# then pivot wider by Run (accession) so that we can calculate all PSI values for a given pos_id
wide_cancer_type_psi <- cancer_type_psi_table |>
  dplyr::select(Run, group, gene_id, pos_id, label, event_type, PSI) |>
  tidyr::pivot_wider(
    names_from = c(Run, group),
    values_from = PSI
  )

```

Run wilcoxon ranksum test
```{r}
# for now convert NA PSI values to 0 (otherwise will get "not enough y observations" in wilcoxon test)
wide_cancer_type_psi[is.na(wide_cancer_type_psi)] <- 0

wilcox_test_events <- wide_cancer_type_psi |>
  # perform wilcoxon ranksum row by row (per pos_id PSI values)
  dplyr::rowwise() |>
  dplyr::mutate(wilcox_p =
                  wilcox.test(
                    dplyr::c_across(ends_with("_ref")),
                    dplyr::c_across(ends_with("_query"))
                  )$p.value) |>
  dplyr::ungroup()
  
# filter for 

```
Filter for distributions that failed the wilcoxon test to see if they look like biologically interesting distributions
```{r}
fail_wilcox_test_events <- wilcox_test_events |>
  dplyr::filter(wilcox_p >= 0.05) |>
  # arbitrarily grab a couple
  

```

